StudentFeedbackWithAuth/Models/Quote.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace StudentFeedbackWithAuth.Models
{
    public class Item
    {
        public string quote { get; set; }
    }
}

StudentFeedbackWithAuth/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentFeedbackWithAuth.Data;
using StudentFeedbackWithAuth.Models;

namespace StudentFeedbackWithAuth.Controllers
{
    public class CourseController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CourseController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Course
        public async Task<IActionResult> Index()
        {
            var courses = await _context.Courses.ToListAsync();
            ClassRatingService rating = new ClassRatingService();

            foreach (Course course in courses)
            {
                var color = rating.SelectClassRatingColor(course);
                course.ratingGrade = color;
            }
            return View(courses);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Course/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,InstructorId")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Course/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Course/FeedbackForm/1
        public async Task<IActionResult> FeedbackForm(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var course = await _context.Courses
            //    .FirstOrDefaultAsync(m => m.Id == id);

            //var questions = await _context.Question
            //    .ToListAsync();

            //var question = from question in _context.Question
            //                join questionnaire in _context.Questionnaires
            //                on question.Id equals questionnaire.QuestionId
            //                where questionnaire.CourseId == id
            //                select new { question };

            //var question = await _context.Question.Join(_context.Questionnaires, qu => qu.Id,
            //    q => q.QuestionId, (q, qu) => new { q, qu })
            //    .Where(x => x.qu.CourseId == id)
            //    .ToListAsync();

            //var questionnaires = await _context.Questionnaires
            //    .Where(x => x.CourseId == id)
            //    .ToListAsync();
            var questions = await _context.Question
                .Where(x => x.Color == id)
                .ToListAsync();

            //List<StudentFeedbackWithAuth.Models.FeedbackQuestion> newList = new List<StudentFeedbackWithAuth.Models.FeedbackQuestion>();
            //foreach (var item in questionnaires)
            //{
            //    StudentFeedbackWithAuth.Models.FeedbackQuestion listItem = new StudentFeedbackWithAuth.Models.FeedbackQuestion();
            //    listItem.Id = item.QuestionId;
            //    var questions = await _context.Question
            //        .Where(x => x.Id == item.QuestionId)
            //        .ToListAsync();
            //    //listItem.Question = questions.Question;
            //    //listItem.ResponseType = questions.ResponseType;
            //    //add your remaining fields
            //    newList.Add(listItem);
            //}

            //var query = from question in _context.Set<FeedbackQuestion>()
            //            join questionnaire in _context.Set<Questionnaire>()
            //                on new { Id = (int?)photo.PersonPhotoId, Caption = photo.Caption }
            //                equals new { Id = person.PhotoId, Caption = "SN" }
            //            select new { person, photo };

            if (questions == null)
            {
                return NotFound();
            }

            return View(questions);
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.Id == id);
        }
    }
}

StudentFeedbackWithAuth/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentFeedbackWithAuth.Data;
using StudentFeedbackWithAuth.Models;

namespace StudentFeedbackWithAuth.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly ApplicationDbContext _context;
        QuestionTypeService qt = new QuestionTypeService();

        public FeedbackController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Feedback
        public async Task<IActionResult> Index()
        {
            var questions = await _context.Question.ToListAsync();

            foreach (FeedbackQuestion question in questions)
            {
                var color = qt.SelectQuestionType(question);
                question.Color = color;
            }
            return View(questions);
        }

        // GET: Feedback/FeedbackForm
        public async Task<IActionResult> FeedbackForm()
        {
            var questions = await _context.Question.ToListAsync();
            MinQuestionsForFeedbackService minQuestions = new MinQuestionsForFeedbackService();
            var minQuestionsAvailable = minQuestions.atLeast2Question(questions.Count);

            if (!minQuestionsAvailable)
            {
                return NotFound();
            }
            return View(questions);
        }

        // GET: Feedback/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedbackQuestions = await _context.Question
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedbackQuestions == null)
            {
                return NotFound();
            }

            return View(feedbackQuestions);
        }

        // GET: Feedback/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Feedback/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Question,ResponseType")] FeedbackQuestion feedbackQuestions)
        {
            if (ModelState.IsValid)
            {
                _context.Add(feedbackQuestions);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(feedbackQuestions);
        }

        // GET: Feedback/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedbackQuestions = await _context.Question.FindAsync(id);
            if (feedbackQuestions == null)
            {
                return NotFound();
            }
            return View(feedbackQuestions);
        }

        // POST: Feedback/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Question,ResponseType")] FeedbackQuestion feedbackQuestions)
        {
            if (id != feedbackQuestions.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(feedbackQuestions);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedbackQuestionsExists(feedbackQuestions.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(feedbackQuestions);
        }

        // GET: Feedback/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedbackQuestions = await _context.Question
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedbackQuestions == null)
            {
                return NotFound();
            }

            return View(feedbackQuestions);
        }

        // POST: Feedback/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var feedbackQuestions = await _context.Question.FindAsync(id);
            _context.Question.Remove(feedbackQuestions);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeedbackQuestionsExists(int id)
        {
            return _context.Question.Any(e => e.Id == id);
        }
    }
}

StudentFeedbackWithAuth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Student Feedback Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-flatly.css" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-secondary mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/sfs_logo2.svg" width="40" height="40">
                    StudentFeedbackSystem
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Feedback" asp-action="Index">Feedback</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - StudentFeedbackWithAuth - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>$(document).ready(function () {
        $('li.active').removeClass('active');
        $('a[href="' + location.pathname + '"]').closest('li').addClass('active');
    });</script>

StudentFeedbackWithAuth/Views/Shared/_Quote.cshtml
<div class="card">
    <div class="card-header">
        <h5 class="card-title"> Quote of the day! </h5>
</div>
    <div class="card-body">
        <blockquote class="blockquote text-center">
            <p class="mb-0">@Model.Quote</p>
            <footer class="blockquote-footer"><cite title="Source Title">@Model.Author</cite></footer>
        </blockquote>
    </div>
</div>

    